import { ManagedTask } from "./types";

export const MOCK_TASKS: ManagedTask[] = [
  {
    id: "tsk_1",
    name: "train-vision-model-nightly",
    status: "running",
    runtimeType: "docker_image",
    executionMode: "deadline",
    provider: "gcp",
    region: "europe-west1",
    createdAt: "2026-03-26T12:00:00.000Z",
    deadline: "2026-03-26T20:00:00.000Z",
    estimatedCo2SavedGrams: 142,
    notes: "Checkpoint every 30 min.",
  },
  {
    id: "tsk_2",
    name: "invoice-lambda-batch",
    status: "scheduled",
    runtimeType: "lambda_code",
    executionMode: "deadline",
    provider: "aws",
    region: "eu-west-1",
    createdAt: "2026-03-26T10:30:00.000Z",
    deadline: "2026-03-26T18:00:00.000Z",
    estimatedCo2SavedGrams: 67,
    notes: "Can wait until grid is greener.",
  },
  {
    id: "tsk_3",
    name: "api-smoke-tests",
    status: "completed",
    runtimeType: "lambda_code",
    executionMode: "immediate",
    provider: "azure",
    region: "westeurope",
    createdAt: "2026-03-26T08:45:00.000Z",
    deadline: null,
    estimatedCo2SavedGrams: 23,
    notes: "Finished in 2m 13s.",
  },
  {
    id: "tsk_4",
    name: "media-thumbnailing",
    status: "failed",
    runtimeType: "docker_image",
    executionMode: "immediate",
    provider: "aws",
    region: "eu-central-1",
    createdAt: "2026-03-26T06:10:00.000Z",
    deadline: null,
    estimatedCo2SavedGrams: 0,
    notes: "Container pull error.",
  },
];
